// pages/account/management/components/BatchAccountDialog.tsx
import { Col, Form, message as $message, Modal, Row, Select } from "antd";
import dynamic from "next/dynamic";
import deepClone from "deep-clone";
import { forwardRef, useEffect, useImperativeHandle, useState } from "react";
import { updateAccount } from "@/api/user";

const Ace = dynamic(() => import("@/components/editor"), { ssr: false });

const BatchAccountDialog = forwardRef(
  ({ accountData, permissionOptions, getAccountData }: any, ref) => {
    const [visible, setVisible] = useState(false);
    const [loading, setLoading] = useState(false);
    const [selected, setSelected] = useState(false);
    const [accountBatchForm] = Form.useForm();

    useImperativeHandle(ref, () => ({
      toggle: (status: boolean) => {
        setVisible(status);
      },
    }));

    const handleOk = async () => {
        setLoading(true);
      accountBatchForm
        .validateFields()
        .then((res) => {
          const copied = deepClone(accountData);
          copied.map((item: any) => (item.permission_id = res.permission_id));

          updateAccount(copied)
            .then(({ msg }) => {
              $message.success(msg);
              setLoading(false);
              setVisible(false);
              getAccountData();
            })
            .catch(() => {
              setLoading(false);
            });
        })
        .catch((e) => {
          $message.error("Please compete the form before submission");
          setLoading(false);
        });
    };

    const findPermission = (id: number) => {
      const foundData = permissionOptions.find((i: any) => i.id === id);
      if (foundData) {
        return JSON.stringify(foundData["permission"], null, 2);
      } else {
        return JSON.stringify({}, null, 2);
      }
    };

    useEffect(() => {
      if (visible) {
        setSelected(false);
        accountBatchForm.setFieldsValue({
          permission_id: null,
          permission: null,
        });
      }
    }, [visible]);

    return (
      <>
        <Modal
          width="800px"
          open={visible}
          okText="update"
          title="Batch Update User Permission"
          maskClosable={false}
          destroyOnClose
          confirmLoading={loading}
          okButtonProps={{
            disabled: !selected,
          }}
          onOk={() => handleOk()}
          onCancel={() => {
            setVisible(false);
            accountBatchForm.resetFields();
          }}
        >
          <Form layout="vertical" form={accountBatchForm}>
            <Row gutter={16}>
              <Col span="24">
                <Form.Item label="Role Selection" name="permission_id" rules={[{ required: true }]}>
                  <Select
                    placeholder="Please Select A Role"
                    fieldNames={{ label: "permission_name", value: "id" }}
                    options={permissionOptions}
                    onChange={(value: number) => {
                      accountBatchForm.setFieldValue("permission", findPermission(value));
                      setSelected(true);
                    }}
                  />
                </Form.Item>
              </Col>
              <Col span="24">
                <Form.Item label="Permission" name="permission">
                  <Ace formRef={accountBatchForm} readOnly={true} />
                </Form.Item>
              </Col>
            </Row>
          </Form>
        </Modal>
      </>
    );
  }
);

export default BatchAccountDialog;

// pages/account/management/components/BatchAccountDialog.vue
<template>
    <a-modal
        v-model:visible="visible"
        width="800px"
        title="Batch Update User Permission"
        :mask-closable="false"
        ok-text="update"
        :confirm-loading="state.loading"
        :ok-button-props="{
            disabled: !canSubmit,
        }"
        @ok="handleOk"
    >
        <a-form ref="formRef" layout="vertical" :model="state.form">
            <a-form-item label="Role Selection" name="permission_id">
                <a-select
                    v-model:value="state.form.permission_id"
                    placeholder="Please Select Role"
                    label-in-value
                    @change="handleRoleChange"
                >
                    <a-select-option
                        v-for="role in state.roles"
                        :key="role.id"
                        :value="role.id"
                        >{{ role.permission_name }}</a-select-option
                    >
                </a-select>
            </a-form-item>
            <a-form-item label="Permission" name="permission">
                <ace-editor v-model:value="state.form.permission" readonly />
            </a-form-item>
        </a-form>
    </a-modal>
</template>
<script setup lang="ts">
import AceEditor from '@/components/AceEditor/index.vue';
import {
    ref,
    reactive,
    watch,
    onMounted,
    computed,
    getCurrentInstance,
} from 'vue';
import { usePermissionStore } from '@/store/modules/permission';

import { updateAccount } from '@/api/user';

const app = getCurrentInstance();
const $message = app.appContext.config.globalProperties.$message;

const props = defineProps<{
    ids: number[];
}>();

const emit = defineEmits(['submit']);
const formRef = ref();
const visible = ref(false);
const permissionStore = usePermissionStore();

const state: {
    form: {
        permission: string;
        role: string;
        permission_id: number | null;
    };
    loading: boolean;
    roles: PERMISSION.PermissionData[];
} = reactive({
    form: {
        permission: '',
        role: '',
        permission_id: null,
    },
    loading: false,
    roles: [],
});

const canSubmit = computed(() => !!state.form.permission_id);

const toggle = () => {
    visible.value = !visible.value;
};

const handleGetRoles = async () => {
    state.roles = await permissionStore.getPermissions();
};

const handleRoleChange = ({ key, label }) => {
    state.form.role = label[0].children;
    handleSetPermission(key);
};

const handleSetPermission = (key: number) => {
    const permission = state.roles.find(({ id }) => key === id)?.permission;
    if (permission) {
        state.form.permission = JSON.stringify(permission, null, 2);
    }
};

const handleOk = async () => {
    try {
        state.loading = true;
        const { permission_id } = state.form;
        const params = props.ids.map((id) => ({ id, permission_id }));
        const { msg } = await updateAccount(params);
        state.loading = false;
        $message.success(msg);
        toggle();
        emit('submit');
    } catch (e) {
        state.loading = false;
        console.log(e);
    }
};

watch(visible, (val) => {
    if (!val) {
        formRef.value.resetFields();
    }
});

onMounted(() => {
    handleGetRoles();
});

defineExpose({
    toggle,
});
</script>
